name: C++ Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up CMake
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake

    - name: Build project
      run: |
        mkdir build
        cd build
        cmake ..
        make
